# Confiuration for connecting to PostgreSQL database
spring.datasource.url=jdbc:postgresql://localhost:5432/server_monitor_db
spring.datasource.username=postgres
spring.datasource.password=alex1234


spring.jpa.hibernate.ddl-auto=update

# Show SQL statements in the console for debugging purposes
spring.jpa.show-sql=true